[workspace]
resolver = "2"
members = ["parse-it", "parse-it-macros", "parse-it-codegen"]

[workspace.dependencies]
proc-macro2 = "1.0.85"
quote = "1.0.36"
syn = { version = "2.0.66", features = ["full", "extra-traits", "visit-mut"] }
rustc-hash = "2.0.0"