[package]
name = "parse-it"
version = "0.0.0"
edition = "2021"
license = "Apache-2.0"

[dependencies]
parse-it-macros = { path = "../parse-it-macros" }
rustc-hash = { workspace = true }
typle = "0.10.6"
