[package]
name = "parse-it"
version = "0.1.0"
edition = "2021"
description = "A user-friendly, opinionated parser generator for Rust."
license = "Apache-2.0"

[dependencies]
parse-it-macros = { version = "0.1.0", path = "../parse-it-macros" }
rustc-hash = { workspace = true }
typle = "0.10.6"
